### ISSUE TITLE
How to use this feature, I'm not able to use this feature in windows.

### ISSUE THREAD

**Issue by sahilrajput03** [OneGraph/graphiql-explorer-example#15]
https://www.onegraph.com/blog/2019/05/30/GraphiQL_Explorer_2_0_A_Power_User_Release.html#jump-to-operation-definition-in-explorer

??

**Comment by sahilrajput03** [comment]
I tried using by clicking while holding ctrl, shift, and alt and any of those combinaitons together, I can't figure it out. Is this feature even works on windows or now?
Thanks.

**Comment by sahilrajput03** [comment]
Whats status on this issue, plesase respond to this thread..

**Comment by sgrove** [comment]
@sahilrajput03 The code for this is relatively small, feel free to [look here](https://github.com/OneGraph/graphiql-explorer-example/blob/master/src/App.js#L95-L98). Are you running this specific repo, and if not, have you added that shortcut?

If you're running this repo, feel free to chance that to some other shortcut that makes more sense for you - maybe "Shift-Alt-LeftClick" is difficult on Windows?

**Comment by sahilrajput03** [comment]
@sgrove Thanks man for replying, seems like i never got the notification for this...

**Comment by sahilrajput03** [comment]
But I managed to work without it without any problem so far..!
